"""Scaffold and aggregate canonical frozen-processor transfer experiments."""

from __future__ import annotations

import argparse
import csv
import json
import os
from copy import deepcopy
from pathlib import Path
from typing import Any

os.environ.setdefault("MPLCONFIGDIR", "/tmp/matplotlib")

import matplotlib

matplotlib.use("Agg")

import matplotlib.pyplot as plt
import numpy as np
import yaml

from src.utils.config import ExperimentConfig, load_config, save_config, validate_config
from src.utils.task_specs import (
    SUPPORTED_ALGORITHM_SPECS,
    normalize_algorithm_order,
    supported_algorithms,
)


DEFAULT_TARGET_CONFIGS = {
    "bf": "configs/bf.yaml",
    "bfs": "configs/bfs.yaml",
    "prim": "configs/prim.yaml",
    "dijkstra": "configs/dijkstra.yaml",
    "dag_shortest_paths": "configs/dag_shortest_paths.yaml",
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Scaffold or aggregate frozen-processor transfer matrices."
    )
    subparsers = parser.add_subparsers(dest="command", required=True)

    scaffold = subparsers.add_parser(
        "scaffold",
        help="Generate one target-task config per source-target transfer pair.",
    )
    scaffold.add_argument("--manifest", type=str, required=True, help="YAML manifest path.")
    scaffold.add_argument(
        "--output-dir",
        type=str,
        required=True,
        help="Directory where generated configs and scripts are written.",
    )

    collect = subparsers.add_parser(
        "collect",
        help="Aggregate finished transfer runs into accuracy matrices.",
    )
    collect.add_argument(
        "--matrix-dir",
        type=str,
        required=True,
        help="Directory previously generated by the scaffold command.",
    )
    collect.add_argument(
        "--run-root",
        type=str,
        default="runs",
        help="Root directory containing run folders.",
    )
    collect.add_argument(
        "--split",
        type=str,
        default="test",
        choices=["val", "test"],
        help="Which split to aggregate from completed runs.",
    )
    collect.add_argument(
        "--output-prefix",
        type=str,
        default=None,
        help="Optional filename prefix for written artifacts. Defaults to the split name.",
    )

    collect_eval = subparsers.add_parser(
        "collect-eval-only",
        help="Aggregate transfer runs from eval-only JSON artifacts.",
    )
    collect_eval.add_argument(
        "--matrix-dir",
        type=str,
        required=True,
        help="Directory previously generated by the scaffold command.",
    )
    collect_eval.add_argument(
        "--run-root",
        type=str,
        default="runs",
        help="Root directory containing run folders.",
    )
    collect_eval.add_argument(
        "--split",
        type=str,
        default="test",
        choices=["val", "test"],
        help="Which split payload to aggregate from eval-only JSON files.",
    )
    collect_eval.add_argument(
        "--eval-file-name",
        type=str,
        default="eval_only.json",
        help="Filename inside each run's analysis directory to read.",
    )
    collect_eval.add_argument(
        "--output-prefix",
        type=str,
        default=None,
        help="Optional filename prefix for written artifacts. Defaults to the split name.",
    )

    audit = subparsers.add_parser(
        "audit",
        help="Verify that source and transfer runs used a standard set of hyperparameters.",
    )
    audit.add_argument(
        "--matrix-dir",
        type=str,
        required=True,
        help="Directory previously generated by the scaffold command.",
    )
    audit.add_argument(
        "--run-root",
        type=str,
        default="runs",
        help="Root directory containing run folders.",
    )
    return parser.parse_args()


def load_yaml(path: Path) -> dict[str, Any]:
    with open(path, "r") as handle:
        data = yaml.safe_load(handle)
    return {} if data is None else data


def load_resolved_manifest_for_matrix_dir(matrix_dir: Path) -> tuple[dict[str, Any], Path]:
    candidates = [
        matrix_dir / "manifest_resolved.json",
        matrix_dir.parent / "manifest_resolved.json",
    ]
    for candidate in candidates:
        if not candidate.exists():
            continue
        with open(candidate, "r") as handle:
            resolved_manifest = json.load(handle)
        config_paths = [
            Path(entry["config_path"])
            for entry in resolved_manifest.get("experiments", [])
            if "config_path" in entry
        ]
        if not config_paths or all(matrix_dir in path.parents for path in config_paths):
            return resolved_manifest, candidate
    raise FileNotFoundError(
        f"Resolved manifest not found for matrix directory: {matrix_dir}"
    )


def apply_overrides(base: dict[str, Any], overrides: dict[str, Any]) -> dict[str, Any]:
    merged = deepcopy(base)
    for key, value in overrides.items():
        if (
            isinstance(value, dict)
            and key in merged
            and isinstance(merged[key], dict)
        ):
            merged[key] = apply_overrides(merged[key], value)
        else:
            merged[key] = deepcopy(value)
    return merged


def latest_checkpoint_from_dir(checkpoints_dir: Path) -> Path:
    latest_file = checkpoints_dir / "latest.json"
    if latest_file.exists():
        with open(latest_file, "r") as handle:
            latest = json.load(handle)
        return checkpoints_dir / latest["checkpoint_name"]
    candidates = sorted(checkpoints_dir.glob("step_*"))
    if not candidates:
        raise FileNotFoundError(f"No checkpoints found under: {checkpoints_dir}")
    return candidates[-1]


def resolve_checkpoint_reference(reference: str | Path) -> Path:
    path = Path(reference)
    if not path.exists():
        raise FileNotFoundError(f"Checkpoint reference not found: {path}")
    if path.is_file():
        return path.parent
    if (path / "checkpoint.json").exists():
        return path
    if path.name == "checkpoints":
        return latest_checkpoint_from_dir(path)
    checkpoints_dir = path / "checkpoints"
    if checkpoints_dir.exists():
        return latest_checkpoint_from_dir(checkpoints_dir)
    raise FileNotFoundError(
        "Checkpoint reference must point to a run directory, a checkpoints "
        f"directory, or a concrete checkpoint directory. Got {path}"
    )


def resolve_run_directory_from_checkpoint(checkpoint_dir: Path) -> Path:
    checkpoint_dir = Path(checkpoint_dir)
    if checkpoint_dir.name.startswith("step_") and checkpoint_dir.parent.name == "checkpoints":
        return checkpoint_dir.parents[1]
    if checkpoint_dir.name == "checkpoints":
        return checkpoint_dir.parent
    if (checkpoint_dir / "config_resolved.yaml").exists():
        return checkpoint_dir
    raise FileNotFoundError(
        "Could not locate config_resolved.yaml for source checkpoint "
        f"{checkpoint_dir}"
    )


def transfer_experiment_name(matrix_name: str, source_id: str, target: str) -> str:
    return f"{matrix_name}__{source_id}__to__{target}"


def primary_metric_for_algorithm(algorithm: str) -> str:
    metrics = [name for name in SUPPORTED_ALGORITHM_SPECS[algorithm]["metric_names"]]
    non_termination = [name for name in metrics if not name.endswith("_termination")]
    if not non_termination:
        raise ValueError(f"No non-termination metrics configured for {algorithm}")
    return non_termination[-1]


def create_model(config: ExperimentConfig):
    from src.model import NGE, AggregationFn

    agg_fn = getattr(AggregationFn, config.model.agg_fn)
    return NGE(
        embed_dim=config.model.embed_dim,
        residual_connections=config.model.residual_connections,
        agg_fn=agg_fn,
        num_mp_layers=config.model.num_mp_layers,
        dropout=config.model.dropout,
        algorithms=tuple(config.model.algorithms),
    )


def flatten_parameter_shapes(tree: Any, prefix: str = "") -> dict[str, tuple[int, ...]]:
    """Flatten nested parameter pytrees into path -> shape mappings."""
    if hasattr(tree, "shape"):
        return {prefix: tuple(int(dim) for dim in tree.shape)}
    if isinstance(tree, dict):
        shapes = {}
        for key, value in tree.items():
            child_prefix = f"{prefix}.{key}" if prefix else str(key)
            shapes.update(flatten_parameter_shapes(value, child_prefix))
        return shapes
    if isinstance(tree, (list, tuple)):
        shapes = {}
        for index, value in enumerate(tree):
            child_prefix = f"{prefix}.{index}" if prefix else str(index)
            shapes.update(flatten_parameter_shapes(value, child_prefix))
        return shapes
    raise TypeError(
        f"Unsupported parameter tree leaf for prefix '{prefix}': {type(tree).__name__}"
    )


def processor_parameter_shapes(model) -> dict[str, tuple[int, ...]]:
    return flatten_parameter_shapes(model.processor.parameters())


def validate_processor_compatibility(
    source_checkpoint: Path,
    target_config: ExperimentConfig,
) -> None:
    source_run_dir = resolve_run_directory_from_checkpoint(source_checkpoint)
    source_config = load_config(source_run_dir / "config_resolved.yaml")
    source_shapes = processor_parameter_shapes(create_model(source_config))
    target_shapes = processor_parameter_shapes(create_model(target_config))
    if source_shapes != target_shapes:
        raise ValueError(
            "Source checkpoint processor is not compatible with the target config. "
            f"Source run={source_run_dir}, source algorithms={source_config.model.algorithms}, "
            f"target algorithms={target_config.model.algorithms}. "
            "Canonical transfer-matrix runs require processor-compatible source checkpoints, "
            "which in practice means using the new single-task source configs."
        )


def build_transfer_pair_config(
    matrix_name: str,
    source_id: str,
    source_checkpoint: Path,
    target: str,
    target_config_path: Path,
    config_overrides: dict[str, Any],
) -> ExperimentConfig:
    base_config = load_config(target_config_path)
    config_dict = base_config.to_dict()
    config_dict["name"] = transfer_experiment_name(matrix_name, source_id, target)
    config_dict["model"]["algorithms"] = [target]
    config_dict["training"]["tasks"] = target
    config_dict["training"]["init_checkpoint"] = str(source_checkpoint)
    config_dict["training"]["init_checkpoint_modules"] = ["processor"]
    config_dict["training"]["freeze_modules"] = ["processor"]
    config_dict["training"]["reset_modules"] = [
        f"{target}_encoder",
        f"{target}_decoder",
        f"{target}_termination",
    ]
    config_dict = apply_overrides(config_dict, config_overrides)
    config = ExperimentConfig.from_dict(config_dict)
    validate_config(config)
    validate_processor_compatibility(source_checkpoint, config)
    return config


def write_matrix_csv(
    output_path: Path,
    row_labels: list[str],
    col_labels: list[str],
    matrix: np.ndarray,
) -> None:
    with open(output_path, "w", newline="") as handle:
        writer = csv.writer(handle)
        writer.writerow(["source"] + col_labels)
        for row_label, values in zip(row_labels, matrix):
            row = [row_label]
            for value in values:
                row.append("" if np.isnan(value) else f"{float(value):.6f}")
            writer.writerow(row)


def plot_matrix_heatmap(
    matrix: np.ndarray,
    row_labels: list[str],
    col_labels: list[str],
    title: str,
    output_path: Path,
    *,
    cmap_name: str = "viridis",
    vmin: float | None = None,
    vmax: float | None = None,
    cbar_label: str = "accuracy",
    signed: bool = False,
) -> None:
    cmap = plt.get_cmap(cmap_name).copy()
    cmap.set_bad("#d9d9d9")
    masked = np.ma.array(matrix, mask=np.isnan(matrix))
    fig, ax = plt.subplots(figsize=(1.3 * len(col_labels) + 2.6, 0.6 * len(row_labels) + 2.8))
    image = ax.imshow(masked, cmap=cmap, vmin=vmin, vmax=vmax, aspect="auto")
    colorbar = fig.colorbar(image, ax=ax)
    colorbar.set_label(cbar_label)
    ax.set_xticks(np.arange(len(col_labels)))
    ax.set_yticks(np.arange(len(row_labels)))
    ax.set_xticklabels(col_labels, rotation=25, ha="right")
    ax.set_yticklabels(row_labels)
    ax.set_xlabel("target task")
    ax.set_ylabel("source processor")
    ax.set_title(title)
    for row_index in range(matrix.shape[0]):
        for col_index in range(matrix.shape[1]):
            value = matrix[row_index, col_index]
            if np.isnan(value):
                ax.text(col_index, row_index, "n/a", ha="center", va="center", fontsize=8)
            else:
                if vmin is not None and vmax is not None and vmax > vmin:
                    normalized = (value - vmin) / (vmax - vmin)
                else:
                    normalized = 0.5
                text_color = "white" if normalized >= 0.6 or normalized <= 0.15 else "black"
                ax.text(
                    col_index,
                    row_index,
                    f"{value:+.2f}" if signed else f"{value:.2f}",
                    ha="center",
                    va="center",
                    fontsize=8,
                    color=text_color,
                )
    fig.tight_layout()
    fig.savefig(output_path, dpi=220, bbox_inches="tight")
    plt.close(fig)


def baseline_by_target(
    matrix: np.ndarray,
    source_ids: list[str],
    targets: list[str],
    fallback_by_target: dict[str, float] | None = None,
) -> np.ndarray:
    """Return the best self-processor score available for each target column."""
    baselines = np.full((len(targets),), np.nan, dtype=np.float64)
    source_index = {source: index for index, source in enumerate(source_ids)}
    for col_index, target in enumerate(targets):
        row_index = source_index.get(target)
        if row_index is None:
            continue
        candidates = []
        diagonal_value = matrix[row_index, col_index]
        if not np.isnan(diagonal_value):
            candidates.append(float(diagonal_value))
        if fallback_by_target is not None:
            fallback_value = fallback_by_target.get(target)
            if fallback_value is not None and not np.isnan(fallback_value):
                candidates.append(float(fallback_value))
        if candidates:
            baselines[col_index] = max(candidates)
    return baselines


def delta_against_baseline(
    matrix: np.ndarray,
    baselines: np.ndarray,
) -> np.ndarray:
    delta = np.full_like(matrix, np.nan, dtype=np.float64)
    for col_index, baseline in enumerate(baselines):
        if np.isnan(baseline):
            continue
        column = matrix[:, col_index]
        valid = ~np.isnan(column)
        delta[valid, col_index] = column[valid] - baseline
    return delta


def scaffold_transfer_matrix(manifest_path: Path, output_dir: Path) -> dict[str, Any]:
    manifest = load_yaml(manifest_path)
    matrix_name = str(manifest.get("name", manifest_path.stem))
    targets = list(
        normalize_algorithm_order(
            manifest.get("targets", list(supported_algorithms()))
        )
    )
    target_configs = dict(DEFAULT_TARGET_CONFIGS)
    target_configs.update(manifest.get("target_configs", {}))
    config_overrides = manifest.get("config_overrides", {})

    sources = manifest.get("sources")
    if not isinstance(sources, dict) or not sources:
        raise ValueError("Manifest must define a non-empty 'sources' mapping.")

    output_dir.mkdir(parents=True, exist_ok=True)
    config_dir = output_dir / "configs"
    config_dir.mkdir(parents=True, exist_ok=True)

    resolved_sources = {
        source_id: str(resolve_checkpoint_reference(reference))
        for source_id, reference in sources.items()
    }

    experiments = []
    command_lines = ["#!/usr/bin/env bash", "set -euo pipefail", ""]
    for source_id, checkpoint_path in resolved_sources.items():
        for target in targets:
            target_config_path = Path(target_configs[target])
            config = build_transfer_pair_config(
                matrix_name=matrix_name,
                source_id=source_id,
                source_checkpoint=Path(checkpoint_path),
                target=target,
                target_config_path=target_config_path,
                config_overrides=config_overrides,
            )
            config_path = config_dir / f"{source_id}__to__{target}.yaml"
            save_config(config, config_path)
            command_lines.append(
                f"python -m src.train --config {config_path}"
            )
            experiments.append(
                {
                    "source": source_id,
                    "target": target,
                    "config_path": str(config_path),
                    "experiment_name": config.name,
                    "primary_metric": primary_metric_for_algorithm(target),
                }
            )

    commands_path = output_dir / "train_commands.sh"
    commands_path.write_text("\n".join(command_lines) + "\n")
    commands_path.chmod(0o755)

    resolved_manifest = {
        "name": matrix_name,
        "manifest_path": str(manifest_path),
        "targets": targets,
        "target_configs": {target: str(target_configs[target]) for target in targets},
        "resolved_sources": resolved_sources,
        "config_overrides": config_overrides,
        "experiments": experiments,
    }

    with open(output_dir / "manifest_resolved.json", "w") as handle:
        json.dump(resolved_manifest, handle, indent=2)

    return resolved_manifest


def find_latest_run_for_name(run_root: Path, experiment_name: str) -> Path | None:
    matches = []
    for run_dir in sorted(run_root.glob("*")):
        if not run_dir.is_dir():
            continue
        config_path = run_dir / "config_resolved.yaml"
        if not config_path.exists():
            continue
        config_data = load_yaml(config_path)
        if config_data.get("name") == experiment_name:
            matches.append(run_dir)
    return matches[-1] if matches else None


def read_latest_split_metrics(run_dir: Path, split: str) -> dict[str, float] | None:
    metrics_path = run_dir / "metrics.jsonl"
    if not metrics_path.exists():
        return None
    latest = None
    with open(metrics_path, "r") as handle:
        for line in handle:
            if not line.strip():
                continue
            entry = json.loads(line)
            if entry.get("split") == split:
                latest = entry["metrics"]
    return latest


def read_eval_only_metrics(
    run_dir: Path,
    split: str,
    eval_file_name: str,
) -> dict[str, float] | None:
    eval_path = run_dir / "analysis" / eval_file_name
    if not eval_path.exists():
        return None
    with open(eval_path, "r") as handle:
        payload = json.load(handle)
    split_payload = payload.get(split)
    if not isinstance(split_payload, dict):
        return None
    latest_file = run_dir / "checkpoints" / "latest.json"
    if latest_file.exists():
        with open(latest_file, "r") as handle:
            latest_info = json.load(handle)
        latest_step = latest_info.get("step")
        eval_step = payload.get("checkpoint_step")
        if latest_step is not None and eval_step is not None and int(eval_step) != int(latest_step):
            raise ValueError(
                f"Stale eval-only artifact detected for {run_dir}: "
                f"{eval_file_name} used checkpoint_step={eval_step}, "
                f"latest available is {latest_step}."
            )
    return split_payload


def source_run_dir_from_resolved_reference(reference: str) -> Path:
    checkpoint_dir = resolve_checkpoint_reference(reference)
    return resolve_run_directory_from_checkpoint(checkpoint_dir)


def collect_transfer_matrix(
    matrix_dir: Path,
    run_root: Path,
    split: str,
    output_prefix: str | None = None,
) -> dict[str, Any]:
    resolved_manifest, resolved_manifest_path = load_resolved_manifest_for_matrix_dir(
        matrix_dir
    )

    source_ids = list(resolved_manifest["resolved_sources"].keys())
    targets = list(resolved_manifest["targets"])
    experiment_index = {
        (entry["source"], entry["target"]): entry
        for entry in resolved_manifest["experiments"]
    }

    all_metrics = set()
    for target in targets:
        all_metrics.update(SUPPORTED_ALGORITHM_SPECS[target]["metric_names"])
    all_metrics = sorted(all_metrics)

    metric_matrices = {
        metric: np.full((len(source_ids), len(targets)), np.nan, dtype=np.float64)
        for metric in all_metrics
    }
    primary_matrix = np.full((len(source_ids), len(targets)), np.nan, dtype=np.float64)
    pair_results = []
    source_baseline_metrics_by_target = {}

    for row_index, source_id in enumerate(source_ids):
        for col_index, target in enumerate(targets):
            entry = experiment_index[(source_id, target)]
            run_dir = find_latest_run_for_name(run_root, entry["experiment_name"])
            pair_result = {
                "source": source_id,
                "target": target,
                "experiment_name": entry["experiment_name"],
                "config_path": entry["config_path"],
                "run_dir": None if run_dir is None else str(run_dir),
                "status": "missing",
            }
            if run_dir is None:
                if source_id == target:
                    source_run_dir = source_run_dir_from_resolved_reference(
                        resolved_manifest["resolved_sources"][source_id]
                    )
                    metrics = read_latest_split_metrics(source_run_dir, split)
                    if metrics is not None:
                        pair_result["run_dir"] = str(source_run_dir)
                        pair_result["status"] = "source_baseline"
                        pair_result["metrics"] = metrics
                        for metric in SUPPORTED_ALGORITHM_SPECS[target]["metric_names"]:
                            metric_key = f"acc/{metric}"
                            if metric_key not in metrics:
                                continue
                            value = float(metrics[metric_key])
                            metric_matrices[metric][row_index, col_index] = value
                            if metric == entry["primary_metric"]:
                                primary_matrix[row_index, col_index] = value
                        pair_results.append(pair_result)
                        continue
                pair_results.append(pair_result)
                continue

            metrics = read_latest_split_metrics(run_dir, split)
            if metrics is None:
                pair_result["status"] = "missing_metrics"
                pair_results.append(pair_result)
                continue

            pair_result["status"] = "ok"
            pair_result["metrics"] = metrics
            for metric in SUPPORTED_ALGORITHM_SPECS[target]["metric_names"]:
                metric_key = f"acc/{metric}"
                if metric_key not in metrics:
                    continue
                value = float(metrics[metric_key])
                metric_matrices[metric][row_index, col_index] = value
                if metric == entry["primary_metric"]:
                    primary_matrix[row_index, col_index] = value
            pair_results.append(pair_result)

    for target in targets:
        source_run_dir = source_run_dir_from_resolved_reference(
            resolved_manifest["resolved_sources"][target]
        )
        metrics = read_latest_split_metrics(source_run_dir, split)
        source_baseline_metrics_by_target[target] = metrics if metrics is not None else {}

    stem = output_prefix or split

    primary_raw_csv = matrix_dir / f"{stem}_primary_transfer_matrix_raw.csv"
    primary_raw_png = matrix_dir / f"{stem}_primary_transfer_matrix_raw.png"
    write_matrix_csv(primary_raw_csv, source_ids, targets, primary_matrix)
    plot_matrix_heatmap(
        primary_matrix,
        row_labels=source_ids,
        col_labels=targets,
        title=f"{stem} primary transfer matrix (raw accuracy)",
        output_path=primary_raw_png,
        cmap_name="viridis",
        vmin=0.0,
        vmax=1.0,
        cbar_label="accuracy",
    )

    primary_baselines = baseline_by_target(
        primary_matrix,
        source_ids,
        targets,
        fallback_by_target={
            target: (
                float(source_baseline_metrics_by_target[target][f"acc/{primary_metric_for_algorithm(target)}"])
                if f"acc/{primary_metric_for_algorithm(target)}" in source_baseline_metrics_by_target[target]
                else np.nan
            )
            for target in targets
        },
    )
    primary_delta = delta_against_baseline(primary_matrix, primary_baselines)
    finite_primary_delta = primary_delta[np.isfinite(primary_delta)]
    primary_delta_absmax = (
        float(np.max(np.abs(finite_primary_delta))) if finite_primary_delta.size else 1.0
    )
    primary_delta_csv = matrix_dir / f"{stem}_primary_transfer_delta.csv"
    primary_delta_png = matrix_dir / f"{stem}_primary_transfer_delta.png"
    write_matrix_csv(primary_delta_csv, source_ids, targets, primary_delta)
    plot_matrix_heatmap(
        primary_delta,
        row_labels=source_ids,
        col_labels=targets,
        title=(
            f"{stem} primary transfer delta "
            "(vs own-processor max)"
        ),
        output_path=primary_delta_png,
        cmap_name="coolwarm",
        vmin=-primary_delta_absmax,
        vmax=primary_delta_absmax,
        cbar_label="accuracy delta",
        signed=True,
    )

    metric_artifacts = {}
    for metric, matrix in metric_matrices.items():
        raw_csv_path = matrix_dir / f"{stem}_{metric}_matrix_raw.csv"
        raw_png_path = matrix_dir / f"{stem}_{metric}_matrix_raw.png"
        write_matrix_csv(raw_csv_path, source_ids, targets, matrix)
        plot_matrix_heatmap(
            matrix,
            row_labels=source_ids,
            col_labels=targets,
            title=f"{stem} {metric} transfer matrix (raw accuracy)",
            output_path=raw_png_path,
            cmap_name="viridis",
            vmin=0.0,
            vmax=1.0,
            cbar_label="accuracy",
        )
        baselines = baseline_by_target(
            matrix,
            source_ids,
            targets,
            fallback_by_target={
                target: (
                    float(source_baseline_metrics_by_target[target][f"acc/{metric}"])
                    if f"acc/{metric}" in source_baseline_metrics_by_target[target]
                    else np.nan
                )
                for target in targets
            },
        )
        delta_matrix = delta_against_baseline(matrix, baselines)
        finite_delta = delta_matrix[np.isfinite(delta_matrix)]
        delta_absmax = float(np.max(np.abs(finite_delta))) if finite_delta.size else 1.0
        delta_csv_path = matrix_dir / f"{stem}_{metric}_delta.csv"
        delta_png_path = matrix_dir / f"{stem}_{metric}_delta.png"
        write_matrix_csv(delta_csv_path, source_ids, targets, delta_matrix)
        plot_matrix_heatmap(
            delta_matrix,
            row_labels=source_ids,
            col_labels=targets,
            title=f"{stem} {metric} delta (vs own-processor max)",
            output_path=delta_png_path,
            cmap_name="coolwarm",
            vmin=-delta_absmax,
            vmax=delta_absmax,
            cbar_label="accuracy delta",
            signed=True,
        )
        metric_artifacts[metric] = {
            "baseline_by_target": {
                target: None if np.isnan(value) else float(value)
                for target, value in zip(targets, baselines)
            },
            "raw_csv": str(raw_csv_path),
            "raw_png": str(raw_png_path),
            "delta_csv": str(delta_csv_path),
            "delta_png": str(delta_png_path),
        }

    summary = {
        "name": resolved_manifest["name"],
        "split": split,
        "matrix_dir": str(matrix_dir),
        "run_root": str(run_root),
        "sources": source_ids,
        "targets": targets,
        "primary_metrics": {
            target: primary_metric_for_algorithm(target) for target in targets
        },
        "primary_baseline_by_target": {
            target: None if np.isnan(value) else float(value)
            for target, value in zip(targets, primary_baselines)
        },
        "primary_matrix_csv": str(primary_delta_csv),
        "primary_matrix_png": str(primary_delta_png),
        "primary_raw_matrix_csv": str(primary_raw_csv),
        "primary_raw_matrix_png": str(primary_raw_png),
        "metric_artifacts": metric_artifacts,
        "pair_results": pair_results,
    }

    with open(matrix_dir / f"{stem}_transfer_matrix_summary.json", "w") as handle:
        json.dump(summary, handle, indent=2)
    return summary


def collect_transfer_matrix_from_eval_only(
    matrix_dir: Path,
    run_root: Path,
    split: str,
    eval_file_name: str,
    output_prefix: str | None = None,
) -> dict[str, Any]:
    resolved_manifest, resolved_manifest_path = load_resolved_manifest_for_matrix_dir(
        matrix_dir
    )

    source_ids = list(resolved_manifest["resolved_sources"].keys())
    targets = list(resolved_manifest["targets"])
    experiment_index = {
        (entry["source"], entry["target"]): entry
        for entry in resolved_manifest["experiments"]
    }

    all_metrics = set()
    for target in targets:
        all_metrics.update(SUPPORTED_ALGORITHM_SPECS[target]["metric_names"])
    all_metrics = sorted(all_metrics)

    metric_matrices = {
        metric: np.full((len(source_ids), len(targets)), np.nan, dtype=np.float64)
        for metric in all_metrics
    }
    primary_matrix = np.full((len(source_ids), len(targets)), np.nan, dtype=np.float64)
    pair_results = []
    source_baseline_metrics_by_target = {}

    for row_index, source_id in enumerate(source_ids):
        for col_index, target in enumerate(targets):
            entry = experiment_index[(source_id, target)]
            run_dir = find_latest_run_for_name(run_root, entry["experiment_name"])
            pair_result = {
                "source": source_id,
                "target": target,
                "experiment_name": entry["experiment_name"],
                "config_path": entry["config_path"],
                "run_dir": None if run_dir is None else str(run_dir),
                "status": "missing",
            }
            if run_dir is None:
                if source_id == target:
                    source_run_dir = source_run_dir_from_resolved_reference(
                        resolved_manifest["resolved_sources"][source_id]
                    )
                    metrics = read_eval_only_metrics(source_run_dir, split, eval_file_name)
                    if metrics is not None:
                        pair_result["run_dir"] = str(source_run_dir)
                        pair_result["status"] = "source_baseline"
                        pair_result["metrics"] = metrics
                        for metric in SUPPORTED_ALGORITHM_SPECS[target]["metric_names"]:
                            metric_key = f"acc/{metric}"
                            if metric_key not in metrics:
                                continue
                            value = float(metrics[metric_key])
                            metric_matrices[metric][row_index, col_index] = value
                            if metric == entry["primary_metric"]:
                                primary_matrix[row_index, col_index] = value
                        pair_results.append(pair_result)
                        continue
                pair_results.append(pair_result)
                continue

            metrics = read_eval_only_metrics(run_dir, split, eval_file_name)
            if metrics is None:
                pair_result["status"] = "missing_metrics"
                pair_results.append(pair_result)
                continue

            pair_result["status"] = "ok"
            pair_result["metrics"] = metrics
            for metric in SUPPORTED_ALGORITHM_SPECS[target]["metric_names"]:
                metric_key = f"acc/{metric}"
                if metric_key not in metrics:
                    continue
                value = float(metrics[metric_key])
                metric_matrices[metric][row_index, col_index] = value
                if metric == entry["primary_metric"]:
                    primary_matrix[row_index, col_index] = value
            pair_results.append(pair_result)

    for target in targets:
        source_run_dir = source_run_dir_from_resolved_reference(
            resolved_manifest["resolved_sources"][target]
        )
        metrics = read_eval_only_metrics(source_run_dir, split, eval_file_name)
        source_baseline_metrics_by_target[target] = metrics if metrics is not None else {}

    stem = output_prefix or split

    primary_raw_csv = matrix_dir / f"{stem}_primary_transfer_matrix_raw.csv"
    primary_raw_png = matrix_dir / f"{stem}_primary_transfer_matrix_raw.png"
    write_matrix_csv(primary_raw_csv, source_ids, targets, primary_matrix)
    plot_matrix_heatmap(
        primary_matrix,
        row_labels=source_ids,
        col_labels=targets,
        title=f"{stem} primary transfer matrix (raw accuracy)",
        output_path=primary_raw_png,
        cmap_name="viridis",
        vmin=0.0,
        vmax=1.0,
        cbar_label="accuracy",
    )

    primary_baselines = baseline_by_target(
        primary_matrix,
        source_ids,
        targets,
        fallback_by_target={
            target: (
                float(
                    source_baseline_metrics_by_target[target][
                        f"acc/{primary_metric_for_algorithm(target)}"
                    ]
                )
                if f"acc/{primary_metric_for_algorithm(target)}"
                in source_baseline_metrics_by_target[target]
                else np.nan
            )
            for target in targets
        },
    )
    primary_delta = delta_against_baseline(primary_matrix, primary_baselines)
    finite_primary_delta = primary_delta[np.isfinite(primary_delta)]
    primary_delta_absmax = (
        float(np.max(np.abs(finite_primary_delta))) if finite_primary_delta.size else 1.0
    )
    primary_delta_csv = matrix_dir / f"{stem}_primary_transfer_delta.csv"
    primary_delta_png = matrix_dir / f"{stem}_primary_transfer_delta.png"
    write_matrix_csv(primary_delta_csv, source_ids, targets, primary_delta)
    plot_matrix_heatmap(
        primary_delta,
        row_labels=source_ids,
        col_labels=targets,
        title=f"{stem} primary transfer delta (vs own-processor max)",
        output_path=primary_delta_png,
        cmap_name="coolwarm",
        vmin=-primary_delta_absmax,
        vmax=primary_delta_absmax,
        cbar_label="accuracy delta",
        signed=True,
    )

    metric_artifacts = {}
    for metric, matrix in metric_matrices.items():
        raw_csv_path = matrix_dir / f"{stem}_{metric}_matrix_raw.csv"
        raw_png_path = matrix_dir / f"{stem}_{metric}_matrix_raw.png"
        write_matrix_csv(raw_csv_path, source_ids, targets, matrix)
        plot_matrix_heatmap(
            matrix,
            row_labels=source_ids,
            col_labels=targets,
            title=f"{stem} {metric} transfer matrix (raw accuracy)",
            output_path=raw_png_path,
            cmap_name="viridis",
            vmin=0.0,
            vmax=1.0,
            cbar_label="accuracy",
        )
        baselines = baseline_by_target(
            matrix,
            source_ids,
            targets,
            fallback_by_target={
                target: (
                    float(source_baseline_metrics_by_target[target][f"acc/{metric}"])
                    if f"acc/{metric}" in source_baseline_metrics_by_target[target]
                    else np.nan
                )
                for target in targets
            },
        )
        delta_matrix = delta_against_baseline(matrix, baselines)
        finite_delta = delta_matrix[np.isfinite(delta_matrix)]
        delta_absmax = float(np.max(np.abs(finite_delta))) if finite_delta.size else 1.0
        delta_csv_path = matrix_dir / f"{stem}_{metric}_delta.csv"
        delta_png_path = matrix_dir / f"{stem}_{metric}_delta.png"
        write_matrix_csv(delta_csv_path, source_ids, targets, delta_matrix)
        plot_matrix_heatmap(
            delta_matrix,
            row_labels=source_ids,
            col_labels=targets,
            title=f"{stem} {metric} delta (vs own-processor max)",
            output_path=delta_png_path,
            cmap_name="coolwarm",
            vmin=-delta_absmax,
            vmax=delta_absmax,
            cbar_label="accuracy delta",
            signed=True,
        )
        metric_artifacts[metric] = {
            "baseline_by_target": {
                target: None if np.isnan(value) else float(value)
                for target, value in zip(targets, baselines)
            },
            "raw_csv": str(raw_csv_path),
            "raw_png": str(raw_png_path),
            "delta_csv": str(delta_csv_path),
            "delta_png": str(delta_png_path),
        }

    summary = {
        "name": resolved_manifest["name"],
        "split": split,
        "matrix_dir": str(matrix_dir),
        "run_root": str(run_root),
        "resolved_manifest_path": str(resolved_manifest_path),
        "eval_file_name": eval_file_name,
        "sources": source_ids,
        "targets": targets,
        "primary_metrics": {
            target: primary_metric_for_algorithm(target) for target in targets
        },
        "primary_baseline_by_target": {
            target: None if np.isnan(value) else float(value)
            for target, value in zip(targets, primary_baselines)
        },
        "primary_matrix_csv": str(primary_delta_csv),
        "primary_matrix_png": str(primary_delta_png),
        "primary_raw_matrix_csv": str(primary_raw_csv),
        "primary_raw_matrix_png": str(primary_raw_png),
        "metric_artifacts": metric_artifacts,
        "pair_results": pair_results,
    }

    with open(matrix_dir / f"{stem}_transfer_matrix_summary.json", "w") as handle:
        json.dump(summary, handle, indent=2)
    return summary


def latest_split_step(run_dir: Path, split: str) -> int | None:
    metrics_path = run_dir / "metrics.jsonl"
    if not metrics_path.exists():
        return None
    latest_step = None
    with open(metrics_path, "r") as handle:
        for line in handle:
            if not line.strip():
                continue
            entry = json.loads(line)
            if entry.get("split") == split:
                latest_step = entry.get("step")
    return latest_step


def audit_transfer_matrix(matrix_dir: Path, run_root: Path) -> dict[str, Any]:
    resolved_manifest, resolved_manifest_path = load_resolved_manifest_for_matrix_dir(
        matrix_dir
    )
    source_ids = list(resolved_manifest["resolved_sources"].keys())
    targets = list(resolved_manifest["targets"])
    experiments = resolved_manifest["experiments"]
    experiment_index = {
        (entry["source"], entry["target"]): entry for entry in experiments
    }

    shared_model_keys = [
        "embed_dim",
        "residual_connections",
        "agg_fn",
        "num_mp_layers",
        "dropout",
        "termination_mode",
        "termination_distance_latent",
        "termination_distance",
        "termination_distance_threshold",
        "termination_distance_signal",
    ]
    shared_training_keys = [
        "epochs",
        "learning_rate",
        "max_grad_norm",
        "batch_size",
        "eval_interval",
        "seed",
    ]
    shared_logging_keys = [
        "log_interval",
        "save_checkpoints",
        "checkpoint_interval",
        "checkpoint_keep_last",
    ]

    issues: list[str] = []
    source_runs = {
        source_id: source_run_dir_from_resolved_reference(reference)
        for source_id, reference in resolved_manifest["resolved_sources"].items()
    }
    source_configs = {
        source_id: load_yaml(run_dir / "config_resolved.yaml")
        for source_id, run_dir in source_runs.items()
    }
    reference_source_id = source_ids[0]
    reference_source_config = source_configs[reference_source_id]

    def shared_snapshot(config_data: dict[str, Any]) -> dict[str, Any]:
        return {
            "model": {
                key: config_data["model"].get(key) for key in shared_model_keys
            },
            "training": {
                key: config_data["training"].get(key) for key in shared_training_keys
            },
            "logging": {
                key: config_data["logging"].get(key) for key in shared_logging_keys
            },
        }

    reference_shared = shared_snapshot(reference_source_config)
    source_audit = {}
    for source_id, run_dir in source_runs.items():
        config_data = source_configs[source_id]
        shared = shared_snapshot(config_data)
        consistent = shared == reference_shared
        if not consistent:
            issues.append(
                f"Source run {run_dir} does not match the shared source hyperparameters."
            )
        test_step = latest_split_step(run_dir, "test")
        expected_epochs = int(config_data["training"]["epochs"])
        if test_step != expected_epochs:
            issues.append(
                f"Source run {run_dir} finished test step {test_step}, expected {expected_epochs}."
            )
        source_audit[source_id] = {
            "run_dir": str(run_dir),
            "shared_hyperparameters": shared,
            "matches_reference": consistent,
            "expected_epochs": expected_epochs,
            "latest_test_step": test_step,
        }

    transfer_audit = {}
    reference_transfer_shared = None
    for source_id in source_ids:
        for target in targets:
            if source_id == target:
                continue
            entry = experiment_index[(source_id, target)]
            run_dir = find_latest_run_for_name(run_root, entry["experiment_name"])
            expected_reset_modules = [
                f"{target}_encoder",
                f"{target}_decoder",
                f"{target}_termination",
            ]
            audit_key = f"{source_id}__to__{target}"
            if run_dir is None:
                issues.append(f"Missing transfer run for {audit_key}.")
                transfer_audit[audit_key] = {
                    "status": "missing_run",
                    "experiment_name": entry["experiment_name"],
                }
                continue
            config_data = load_yaml(run_dir / "config_resolved.yaml")
            shared = shared_snapshot(config_data)
            if reference_transfer_shared is None:
                reference_transfer_shared = shared
            consistent = shared == reference_transfer_shared == reference_shared
            if not consistent:
                issues.append(
                    f"Transfer run {run_dir} does not match the standard shared hyperparameters."
                )
            expected_init = str(resolve_checkpoint_reference(
                resolved_manifest["resolved_sources"][source_id]
            ))
            invariants = {
                "algorithms": config_data["model"].get("algorithms"),
                "tasks": config_data["training"].get("tasks"),
                "init_checkpoint": config_data["training"].get("init_checkpoint"),
                "init_checkpoint_modules": config_data["training"].get(
                    "init_checkpoint_modules"
                ),
                "freeze_modules": config_data["training"].get("freeze_modules"),
                "reset_modules": config_data["training"].get("reset_modules"),
            }
            invariant_ok = (
                invariants["algorithms"] == [target]
                and invariants["tasks"] == target
                and invariants["init_checkpoint"] == expected_init
                and invariants["init_checkpoint_modules"] == ["processor"]
                and invariants["freeze_modules"] == ["processor"]
                and invariants["reset_modules"] == expected_reset_modules
            )
            if not invariant_ok:
                issues.append(
                    f"Transfer run {run_dir} violates the canonical frozen-processor invariants."
                )
            test_step = latest_split_step(run_dir, "test")
            expected_epochs = int(config_data["training"]["epochs"])
            if test_step != expected_epochs:
                issues.append(
                    f"Transfer run {run_dir} finished test step {test_step}, expected {expected_epochs}."
                )
            transfer_audit[audit_key] = {
                "status": "ok",
                "run_dir": str(run_dir),
                "shared_hyperparameters": shared,
                "matches_reference": consistent,
                "invariants_ok": invariant_ok,
                "invariants": invariants,
                "expected_epochs": expected_epochs,
                "latest_test_step": test_step,
            }

    summary = {
        "matrix_dir": str(matrix_dir),
        "resolved_manifest_path": str(resolved_manifest_path),
        "run_root": str(run_root),
        "sources": source_ids,
        "targets": targets,
        "reference_shared_hyperparameters": reference_shared,
        "source_runs": source_audit,
        "transfer_runs": transfer_audit,
        "all_shared_hyperparameters_standard": not issues,
        "issues": issues,
    }
    output_path = matrix_dir / "run_consistency_audit.json"
    with open(output_path, "w") as handle:
        json.dump(summary, handle, indent=2)
    summary["output_path"] = str(output_path)
    return summary


def main() -> None:
    args = parse_args()
    if args.command == "scaffold":
        result = scaffold_transfer_matrix(Path(args.manifest), Path(args.output_dir))
        print(f"Saved transfer-matrix scaffold to: {args.output_dir}")
        print(f"Generated {len(result['experiments'])} pair configs.")
        print(f"Training commands: {Path(args.output_dir) / 'train_commands.sh'}")
        return
    if args.command == "audit":
        summary = audit_transfer_matrix(
            matrix_dir=Path(args.matrix_dir),
            run_root=Path(args.run_root),
        )
        status = "standard" if summary["all_shared_hyperparameters_standard"] else "issues"
        print(
            f"Saved transfer-matrix audit to: {summary['output_path']} "
            f"({status}, {len(summary['issues'])} issue(s))"
        )
        return

    if args.command == "collect":
        summary = collect_transfer_matrix(
            matrix_dir=Path(args.matrix_dir),
            run_root=Path(args.run_root),
            split=args.split,
            output_prefix=args.output_prefix,
        )
        print(
            f"Saved {args.split} transfer delta matrix to: "
            f"{summary['primary_matrix_csv']} and {summary['primary_matrix_png']}"
        )
        return

    summary = collect_transfer_matrix_from_eval_only(
        matrix_dir=Path(args.matrix_dir),
        run_root=Path(args.run_root),
        split=args.split,
        eval_file_name=args.eval_file_name,
        output_prefix=args.output_prefix,
    )
    print(
        f"Saved {args.split} eval-only transfer delta matrix to: "
        f"{summary['primary_matrix_csv']} and {summary['primary_matrix_png']}"
    )


if __name__ == "__main__":
    main()
